import Head from "next/head";
import Image from "next/image";

export default function Home({ matches }) {
  console.log(matches);
  return (
    <>
      <Head>
        <title>WorldCupAPI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

//reglas de next , llamar api del lado servidor
export const getServerSideProps = async (context) => {
  const token =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDNmMjQ4OTRkZjc2OTcxNzU2NjE1ZjUiLCJpYXQiOjE2ODE4NjAxOTksImV4cCI6MTY4MTk0NjU5OX0.aG-X_JFkAwVwsi-w6q-eesqTy9v7f1AJg8lf-14wI2s";
  const headers = {
    Authorization: "Bearer " + token,
  };
  const res = await fetch("http://api.cup2022.ir/api/v1/match", { headers });
  const matches = await res.json();

  return {
    props: {
      matches: matches,
    },
  };
};
